import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "About Next js",
    template: "%s | Blog",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          margin: 0,
          padding: 0,
          fontFamily: "sans-serif",
          backgroundColor: "#000000",
          color: "#e0e0e0",
        }}
      >
        <header
          style={{
            backgroundColor: "#0a84ff",
            color: "#ffffff",
            padding: "20px",
            textAlign: "center",
            fontSize: "24px",
            fontWeight: "bold",
          }}
        >
          My Website Header
        </header>

        <main style={{ padding: "20px" }}>{children}</main>

        <footer
          style={{
            backgroundColor: "#0a84ff",
            color: "#ffffff",
            padding: "15px",
            textAlign: "center",
            fontSize: "24px",
            marginTop: "40px",
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
